### ISSUE TITLE
[feature] newsletter subscription form should work serverless

### ISSUE THREAD

**Issue by AlburIvan** [MaG21/MaG21.github.io#3]
The idea behind it is to integrate the form with AWS Lambda, for a serverless architecture and less server overhead. For that we need a developers account to create the AWS account, if we do not already posses one.

- [x] Get developers@erabo account (@MaG21 need your help)
- [x] Create AWS root account
- [ ] Configure IAM roles and account for each member
- [x] Figure out where will the mails be saved to
- [x] Implement AWS lambda call in page

**Comment by MaG21** [comment]
Listo, ya el correo developers fue generado. Necesitaría tu correo electrónico, para mandarte forawards automáticos

**Comment by AlburIvan** [comment]
AWS account was created successfully

Email: developers@erabo.app
Pass: via slack

Going to create accounts for each of you now

**Comment by AlburIvan** [comment]
This feature is live, as per PR #13.

The accounts will be created on monday as its easier for communication, in case y'all need something
